//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labora_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblNotasEstudiante
    {
        public int IdEstudiante { get; set; }
        public string Nombre { get; set; }
        public string lab1 { get; set; }
        public string lab2 { get; set; }
        public string lab3 { get; set; }
        public string par1 { get; set; }
        public string par2 { get; set; }
        public string par3 { get; set; }
    }
}
